apiVersion: v1
kind: Service
metadata:
  name: publisher-service
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: ap-ims
    tier: backend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: publisher-deployment
spec:
  revisionHistoryLimit: 2
  replicas: 2
  strategy:
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: publisher-service
        tier: backend
    spec:
      containers:
      - name: ap-ims
        image: @docker_repository@/publisher-service:@version_publisher@
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /manage/health.json
            port: 8080
            scheme: HTTP
          periodSeconds: 120
          timeoutSeconds: 120
        resources:
          requests:
            cpu: 200m
            memory: 1024M
          limits:
            cpu: 400m
            memory: 2048M
        env:
        - name: GET_HOSTS_FROM
          value: dns
        - name: CONFIG_SERVICE_URL
          value: "@config_service_hostname@"
        - name: CONFIG_SERVICE_ENABLED
          value: "true"
        - name: JAVA_OPTS
          value: "-Xmx1536m"
        ports:
        - containerPort: 8080
